title: . A
author: Albert Hardy
email: albert@tanutama.com
description: > # this means to ignore newlines until "baseurl:"
  Designer, Improviser and Researcher of Structure and Harmony. 
  Coherence is irresistible.

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

name: Albert Hardy
job: Designer
location: Singapore
languages: HTML, CSS and Javascript
twitter_username: alberthardy
# email_address: some@email.com
# github_username:  jonathandoe
# codepen_username:  jonathandoe

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#- about.md
#- concepts/index.html

article_navigation:
- title: Archive
  url: /notes/archive/   
- title: Category
  url: /notes/category/  
- title: Tag
  url: /notes/tag/   

#https://jekyllrb.com/docs/permalinks/
permalink: "/notes/:year/:month/:title/"

# excerpt_separator
# http://www.seanbuscay.com/blog/jekyll-teaser-pager-and-read-more/
excerpt_separator: <!--more-->

# Gems
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/notes/page:num"

# Build Collections
# https://learn.cloudcannon.com/jekyll/introduction-to-jekyll-collections/
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

